---- OWNERS DATA INSERTION-----
CREATE SEQUENCE OWNER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 100
MINVALUE 0
NOCYCLE
NOCACHE;


INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'John Doe', '123 Main St, Springfield', '9876543210', 'ABC123456');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Jane Smith', '456 Oak Rd, Springfield', '9876543211', 'XYZ987654');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Alice Johnson', '789 Pine Ave, Springfield', '9876543212', 'LMN456789');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Bob Brown', '101 Maple Dr, Springfield', '9876543213', 'OPQ321654');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Charlie Davis', '202 Birch Ln, Springfield', '9876543214', 'DEF234567');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'David Wilson', '303 Cedar Blvd, Springfield', '9876543215', 'GHI345678');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Eva Martinez', '404 Elm St, Springfield', '9876543216', 'JKL456789');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Frank Thomas', '505 Redwood Rd, Springfield', '9876543217', 'MNO567890');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Grace Lee', '606 Willow St, Springfield', '9876543218', 'PQR678901');

INSERT INTO OWNERS (OWNER_ID, NAME, ADDRESS, PHONE, LICENSE_NUMBER) 
VALUES (OWNER_SEQ.NEXTVAL, 'Henry White', '707 Oak Dr, Springfield', '9876543219', 'STU789012');
--------------------------------------------------------------------------------------------

----ONWERS INSURANCE
CREATE SEQUENCE OI_SEQ
START WITH 101
INCREMENT BY 1
MAXVALUE 1000
MINVALUE 0
NOCYCLE
NOCACHE;


INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-01', 'YYYY-MM-DD'), 'Comprehensive');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 2, TO_DATE('2023-05-15', 'YYYY-MM-DD'), TO_DATE('2024-05-15', 'YYYY-MM-DD'), 'Third Party');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 3, TO_DATE('2022-07-20', 'YYYY-MM-DD'), TO_DATE('2023-07-20', 'YYYY-MM-DD'), 'Comprehensive');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 4, TO_DATE('2021-09-01', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 'Third Party');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 5, TO_DATE('2022-03-10', 'YYYY-MM-DD'), TO_DATE('2023-03-10', 'YYYY-MM-DD'), 'Comprehensive');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 6, TO_DATE('2023-08-05', 'YYYY-MM-DD'), TO_DATE('2024-08-05', 'YYYY-MM-DD'), 'Third Party');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 7, TO_DATE('2022-11-15', 'YYYY-MM-DD'), TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'Comprehensive');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 8, TO_DATE('2021-05-30', 'YYYY-MM-DD'), TO_DATE('2022-05-30', 'YYYY-MM-DD'), 'Third Party');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 9, TO_DATE('2023-06-18', 'YYYY-MM-DD'), TO_DATE('2024-06-18', 'YYYY-MM-DD'), 'Comprehensive');

INSERT INTO OWNER_INSURANCE (OWNER_INSURANCE_ID, OWNER_ID, START_DATE, END_DATE, TYPE) 
VALUES (OI_SEQ.NEXTVAL, 10, TO_DATE('2022-02-25', 'YYYY-MM-DD'), TO_DATE('2023-02-25', 'YYYY-MM-DD'), 'Third Party');


------------------------------------------------------------------------------------------------------------------------
----VEHICLE DATA 
CREATE SEQUENCE VINDX
START WITH 2000
INCREMENT BY 1
MAXVALUE 5000
MINVALUE 0
NOCYCLE
NOCACHE;

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Car', 1234567890, 1, 5.2, 'Good');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Truck', 2345678901, 2, 3.5, 'Excellent');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Car', 3456789012, 3, 8.0, 'Fair');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Bus', 4567890123, 4, 12.5, 'Poor');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Truck', 5678901234, 5, 6.1, 'Good');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Car', 6789012345, 6, 4.7, 'Excellent');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Bus', 7890123456, 7, 9.2, 'Fair');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Car', 8901234567, 8, 3.4, 'Good');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Truck', 9012345678, 9, 7.3, 'Excellent');

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, LICENSE_PLATE, OWNER_ID, VEHICLE_AGE, VEHICLE_CONDITION) 
VALUES (VINDX.NEXTVAL, 'Bus', 0123456789, 10, 5.9, 'Poor');

-----------------------------------------------------------------------------------------------------------

--- VEHICLE INSURANCE
CREATE SEQUENCE VIDEX
START WITH 7000
INCREMENT BY 1
MAXVALUE 10000
MINVALUE 0
NOCYCLE
NOCACHE;


INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2000, 'Comprehensive', DATE '2023-01-01', DATE '2024-01-01');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2001, 'Third-Party', DATE '2023-02-15', DATE '2024-02-15');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2002, 'Collision Coverage', DATE '2023-03-10', DATE '2024-03-10');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2003, 'Comprehensive', DATE '2023-04-20', DATE '2024-04-20');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2004, 'Liability', DATE '2023-05-05', DATE '2024-05-05');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2005, 'Personal Injury Protection', DATE '2023-06-15', DATE '2024-06-15');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2006, 'Collision Coverage', DATE '2023-07-01', DATE '2024-07-01');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2007, 'Comprehensive', DATE '2023-08-10', DATE '2024-08-10');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2008, 'Liability', DATE '2023-09-25', DATE '2024-09-25');

INSERT INTO VINSURANCE (VI_ID, VEHICLE_ID, TYPE, START_DATE, END_DATE) 
VALUES (VIDEX.NEXTVAL, 2009, 'Third-Party', DATE '2023-10-30', DATE '2024-10-30');
---------------------------------------------------------------------------------------
---LOCATIONS
CREATE SEQUENCE LOIDX
START WITH 3000
INCREMENT BY 1
MAXVALUE 5000
MINVALUE 0
NOCYCLE
NOCACHE;

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'New York', 'New York', 10001, 'Highway');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'Los Angeles', 'California', 90001, 'Main Road');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'Chicago', 'Illinois', 60601, 'Street');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'Houston', 'Texas', 77001, 'Avenue');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'Phoenix', 'Arizona', 85001, 'Expressway');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'Philadelphia', 'Pennsylvania', 19101, 'Boulevard');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'San Antonio', 'Texas', 78201, 'Lane');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'San Diego', 'California', 92101, 'Drive');

INSERT INTO LOCATIONS1 (LOCATION_ID, CITY, STATE, ZIP_CODE, ROAD_TYPE) 
VALUES (LOIDX.NEXTVAL, 'Dallas', 'Texas', 75201, 'Circle');


---------------------------------------------------------------
---- ACCIDENTS

CREATE SEQUENCE ACCIDX
START WITH 4000
INCREMENT BY 1
MAXVALUE 10000
MINVALUE 0
NOCYCLE
NOCACHE;

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-02-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 2000, 3000, 'Rear-end collision on highway');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-02-05', 'YYYY-MM-DD'), SYSTIMESTAMP, 2001, 3001, 'Side-impact collision at intersection');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-02-10', 'YYYY-MM-DD'), SYSTIMESTAMP, 2002, 3002, 'Multi-vehicle pileup due to fog');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-02-15', 'YYYY-MM-DD'), SYSTIMESTAMP, 2003, 3003, 'Hit and run reported on expressway');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-02-20', 'YYYY-MM-DD'), SYSTIMESTAMP, 2004, 3004, 'Truck lost control on slippery road');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-02-25', 'YYYY-MM-DD'), SYSTIMESTAMP, 2005, 3005, 'Motorcycle accident due to speed');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-03-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 2006, 3006, 'Car overturned on sharp turn');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-03-05', 'YYYY-MM-DD'), SYSTIMESTAMP, 2007, 3007, 'Pedestrian hit while crossing street');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-03-10', 'YYYY-MM-DD'), SYSTIMESTAMP, 2008, 3008, 'Brake failure caused chain collision');

INSERT INTO ACCIDENTS (ACCIDENT_ID, DATE1, TIME, VEHICLE_ID, LOCATION_ID, DESCRIPTIONS) 
VALUES (ACCIDX.NEXTVAL, TO_DATE('2024-03-15', 'YYYY-MM-DD'), SYSTIMESTAMP, 2009, 3009, 'Car caught fire after collision');
'California', 95101, 'Route');
--------------------------------------------------------------------------------------------

-- INJURY
CREATE SEQUENCE IIDENX
START WITH 5000
INCREMENT BY 1
MAXVALUE 10000
MINVALUE 0
NOCYCLE 
NOCACHE;


TRUNCATE TABLE INJURY;

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Fracture', 'Severe', 'Multiple bone fractures in the leg and arm.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Head Injury', 'Critical', 'Severe head trauma with internal bleeding.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Whiplash', 'Moderate', 'Neck strain due to sudden impact.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Burns', 'Severe', 'Third-degree burns caused by vehicle fire.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Laceration', 'Moderate', 'Deep cuts and wounds requiring stitches.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Internal Bleeding', 'Critical', 'Internal organ damage with severe bleeding.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Concussion', 'Mild', 'Mild head trauma with temporary dizziness.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Spinal Cord Injury', 'Severe', 'Partial paralysis due to spinal damage.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Bruises', 'Mild', 'Minor bruises on arms and legs.');

INSERT INTO INJURY (INJURY_ID, INJURY_TYPE, SEVERITY, DESCRIPTIONS) 
VALUES (IIDENX.NEXTVAL, 'Broken Ribs', 'Moderate', 'Multiple rib fractures causing breathing difficulty.');

-------------------------------------------------------------------------------------------------------------

----- VICTIMS
CREATE SEQUENCE VIINDEX
START WITH 6000
INCREMENT BY 1
MAXVALUE 10000
MINVALUE 0
NOCYCLE 
NOCACHE;



INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4001, 'John Doe', 35, 5000, 'Critical');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4002, 'Jane Smith', 28, 5001, 'Deceased');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4003, 'Michael Johnson', 42, 5002, 'Recovering');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4004, 'Emily Davis', 30, 5003, 'Severe Condition');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4005, 'David Brown', 50, 5004, 'Stable');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4006, 'Sarah Wilson', 24, 5005, 'Under Observation');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4007, 'Robert White', 38, 5006, 'Discharged');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4008, 'Sophia Miller', 22, 5007, 'Mild Injury');

INSERT INTO VICTIMS (VICTIM_ID, ACCIDENT_ID, NAME, AGE, INJURY_ID, STATUS) 
VALUES (VIINDEX.NEXTVAL, 4009, 'James Anderson', 60, 5008, 'Severe Condition');


